INSERT INTO PROFILES (ID) VALUES ('lameiraatt');
INSERT INTO PROFILES (ID) VALUES ('astroash');
INSERT INTO PROFILES (ID) VALUES ('i-bm');
INSERT INTO PROFILES (ID) VALUES ('dawudmohammed');
INSERT INTO PROFILES (ID) VALUES ('theGeniusBintu');
